import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: 'width=device-width, initial-scale=1.0',
};
// width=device-width - บอกให้เบราว์เซอร์ใช้ความกว้างของอุปกรณ์จริงเป็นความกว้างของ viewport (พื้นที่แสดงผล)
// initial-scale=1.0 - กำหนดระดับการซูมเริ่มต้นเป็น 1.0 (ไม่มีการซูมเข้าหรือออก)


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
